baseURL = 'https://blog-2026-two.vercel.app/'
languageCode = 'zh-cn'
title = 'zyj的秘密基地'
theme = 'PaperMod'

[params]
    env = "production"
    title = "我的博客"
    author = "libzwo"
    description = "记录生活，分享经验"

[author]
    name = "libzwo"

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[markup.goldmark.renderer]
    unsafe = true
